### ISSUE TITLE
When clicking onthe crop button in the lightboxes scrollbars appear

### ISSUE THREAD

**Issue by nebulousGirl** [sirulli/yoimages#41]
While fiddling with browser inspector, this fixed it: 
```css
.yoimg-crop-now-wrapper {float: left;width: 100%;padding-bottom: 5px;}
```

I don't have time to do a pull request right now. If anyone wants to fix it, go ahead, else I will do it when I have the time.
